[project]
name = "suite2p-haisslab"
description = "Pipeline for calcium imaging"
authors = [
    { name = "Marius Pachitariu" },
    { name = "Carsen Stringer" },
    { name = "Timothe Jost-Mousseau", email = "timothe.jost-mousseau@pasteur.fr" },
]
version = "1.0.0.2"
dependencies = [
    "natsort",
    "tifffile",
    "torch>=1.13.1",
    "numpy>=1.24.3",
    "numba>=0.57.0",
    "matplotlib",
    "scipy>=1.9.0",
    "scikit-learn",
    "cellpose>=4.0.1",
    "scanimage-tiff-reader>=1.4.1",
]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "GPLv3" }
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.urls]
Source = "https://github.com/JostTim/suite2p"
PyPi = "https://pypi.org/project/suite2p-haisslab/"

[project.optional-dependencies]
gui = ["qtpy", "superqt", "pyqt6", "pyqt6.sip", "pyqtgraph", "rastermap>=0.9.0"]
nwb = ["pynwb>=2.3.2"]
io = [
    "h5py",
    "nd2",
    "opencv-python-headless",
    "paramiko",
    "sbxreader",
    "xmltodict",
    "dcimg",
]
tests = [
    "pytest",
    "tenacity",
    "tqdm",
    "pynwb>=2.3.2",    #this is needed as test_io contains a test with nwb
    "pytest-qt>3.3.0",
]

[project.scripts]
suite2p = "suite2p.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.bumpversion]
files = [
    { filename = "suite2p/version.py", search = "version = \"{current_version}\"", replace = "version = \"{new_version}\"" },
    { filename = "pyproject.toml", search = "version = \"{current_version}\"", replace = "version = \"{new_version}\"" },
]
current_version = "1.0.0.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+).(?P<commit>\\d+)"
serialize = ["{major}.{minor}.{patch}.{commit}"]
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = "--no-verify"
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []
